language: php

php:
   - 7.0
   - 7.1
   - 7.2
   - 7.3

env:
   - ILLUMINATE_VERSION=5.5.* PHPUNIT_VERSION=~6.0
   - ILLUMINATE_VERSION=5.6.* PHPUNIT_VERSION=~7.0
   - ILLUMINATE_VERSION=5.7.* PHPUNIT_VERSION=~7.0
   - ILLUMINATE_VERSION=5.8.* PHPUNIT_VERSION=~7.0

matrix:
   fast_finish: true
   exclude:
      - php: 7.0
        env: ILLUMINATE_VERSION=5.6.* PHPUNIT_VERSION=~7.0
      - php: 7.0
        env: ILLUMINATE_VERSION=5.7.* PHPUNIT_VERSION=~7.0
      - php: 7.0
        env: ILLUMINATE_VERSION=5.8.* PHPUNIT_VERSION=~7.0

before_install:
   - composer require "illuminate/support:${ILLUMINATE_VERSION}" --no-update --prefer-dist
   - composer require "illuminate/contracts:${ILLUMINATE_VERSION}" --no-update --prefer-dist
   - composer require "illuminate/view:${ILLUMINATE_VERSION}" --no-update --prefer-dist
   - composer require "phpunit/phpunit:${PHPUNIT_VERSION}" --no-update --prefer-dist
   - composer require "orchestra/testbench:${ILLUMINATE_VERSION/5\./3\.}" --no-update --prefer-dist

install: travis_retry composer install --no-interaction --prefer-dist

script:
   - phpunit
